# Generated by Django 2.0.1 on 2018-01-22 22:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooking',
            name='task_completed',
        ),
        migrations.AddField(
            model_name='cooking',
            name='URL_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cooking',
            name='course',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Soup', 'Soup'), ('Side Dish', 'Side Dish'), ('Appetizer', 'Appetizer'), ('Salad', 'Salad'), ('Dessert', 'Dessert'), ('Drink', 'Drink'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cooking',
            name='meat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Turkey', 'Turkey'), ('Seafood', 'Seafood'), ('None', 'None')], max_length=37, null=True),
        ),
        migrations.AddField(
            model_name='cooking',
            name='specifics',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
