# Generated by Django 2.0.1 on 2018-01-22 23:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20180122_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooking',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cooking',
            name='meat',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Turkey', 'Turkey'), ('Seafood', 'Seafood'), ('None', 'None')], default='None', max_length=37, null=True),
        ),
    ]
