# Generated by Django 2.0.1 on 2018-01-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_auto_20180122_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooking',
            old_name='specifics',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='cooking',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
