# Generated by Django 2.0.1 on 2018-01-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_auto_20180122_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooking',
            name='tinymce_test',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
