# Generated by Django 2.0.1 on 2018-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_cooking_tinymce_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking',
            name='tinymce_test',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
