# Generated by Django 2.0.1 on 2018-01-18 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=100, null=True)),
                ('post_category', models.CharField(blank=True, choices=[('Daily Entry', 'Daily Entry'), ('Personal Thoughts', 'Personal Thoughts'), ('Professional', 'Professional')], default='Daily Entry', max_length=50, null=True)),
                ('post_entry', models.TextField(blank=True, max_length=10000, null=True)),
                ('public_private', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Private', 'Private'), ('Subscribers', 'Subscribers'), ('Public', 'Public')], default='Private', max_length=26, null=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_added'],
            },
        ),
    ]
