# Generated by Django 2.0.1 on 2018-01-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humancapitalpost',
            name='public_or_private',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='humancapitalpost',
            name='upload_file',
            field=models.FileField(blank=True, default='None', null=True, upload_to='humancapital/posts/%Y/'),
        ),
    ]
