# Generated by Django 2.0.1 on 2018-01-22 23:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0002_auto_20180119_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humancapitaljargon',
            name='relates_to',
            field=models.CharField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='humancapitaljargon',
            name='word_or_phrase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Term or Acronym'),
        ),
        migrations.AlterField(
            model_name='humancapitalpost',
            name='post_topic',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
    ]
