# Generated by Django 2.0.1 on 2018-01-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humancapital', '0003_auto_20180122_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanCapitalSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(blank=True, max_length=200, null=True)),
                ('topic', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True)),
                ('upload_file', models.FileField(blank=True, default='None', null=True, upload_to='humancapital/posts/%Y/')),
                ('url_link', models.URLField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_added'],
            },
        ),
    ]
