# Generated by Django 2.0.1 on 2018-01-26 17:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0004_humancapitalsource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humancapitalsource',
            old_name='upload_file',
            new_name='upload_file_1',
        ),
        migrations.RenameField(
            model_name='humancapitalsource',
            old_name='url_link',
            new_name='url_link_1',
        ),
        migrations.AddField(
            model_name='humancapitalsource',
            name='upload_file_2',
            field=models.FileField(blank=True, default='None', null=True, upload_to='humancapital/posts/%Y/'),
        ),
        migrations.AddField(
            model_name='humancapitalsource',
            name='upload_file_3',
            field=models.FileField(blank=True, default='None', null=True, upload_to='humancapital/posts/%Y/'),
        ),
        migrations.AddField(
            model_name='humancapitalsource',
            name='url_link_2',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='humancapitalsource',
            name='url_link_3',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='humancapitaljargon',
            name='relates_to',
            field=models.CharField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Diversity + Inclusion', 'Diversity + Inclusion'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='humancapitalpost',
            name='post_topic',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Diversity + Inclusion', 'Diversity + Inclusion'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='humancapitalsource',
            name='topic',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('General Human Capital', 'General Human Capital'), ('Change Mgmt + Communications', 'Change Mgmt + Communications'), ('Leadership + Management', 'Leadership + Management'), ('Org Design', 'Org Design'), ('Culture', 'Culture'), ('Talent Acquisition', 'Talent Acquisition'), ('Talent Mgmt + Retention', 'Talent Mgmt + Retention'), ('Performance Management', 'Performance Management'), ('Diversity + Inclusion', 'Diversity + Inclusion'), ('Pay & Benefits', 'Pay & Benefits'), ('Learning & Development', 'Learning & Development'), ('Training', 'Training'), ('HR Strategies + Services', 'HR Strategies + Services'), ('Tech Adoption', 'Tech Adoption'), ('Mergers & Acquisitions', 'Mergers & Acquisitions')], max_length=100, null=True),
        ),
    ]
