# Generated by Django 2.0.1 on 2018-01-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, default='Food', max_length=100, null=True)),
                ('amount', models.CharField(blank=True, default='1', max_length=4, null=True)),
                ('item_category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Medicine/Hygene', 'Medicine/Hygene'), ('Electronics', 'Electronics'), ('Sports/Recreation', 'Sports/Recreation')], default='Food', max_length=59, null=True)),
                ('store_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Grocery', 'Grocery'), ('Online', 'Online'), ('Walmart', 'Walmart'), ('Drug Store', 'Drug Store'), ('Shopping Mall', 'Shopping Mall'), ('Other', 'Other')], default='Grocery', max_length=53, null=True)),
                ('recipient', models.CharField(blank=True, default='Shared', max_length=50, null=True)),
                ('urgency', models.CharField(blank=True, choices=[('Now', 'Now'), ('Soon', 'Soon'), ('Considering', 'Considering'), ('Do not need', 'Do not need')], default='Now', max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, max_length=75, null=True)),
                ('item_url', models.URLField(blank=True, max_length=500, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('max_spend', models.CharField(blank=True, max_length=10, null=True)),
                ('specifics', models.TextField(blank=True, max_length=1000, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_added'],
            },
        ),
    ]
