# Generated by Django 2.0.1 on 2018-01-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='item_category',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Medicine/Hygene', 'Medicine/Hygene'), ('Household', 'Household'), ('Work', 'Work'), ('Personal Want', 'Personal Want')], default='Food', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='recipient',
            field=models.CharField(blank=True, choices=[('Shared', 'Shared'), ('Dan', 'Dan'), ('Alice', 'Alice'), ('Gift for Other', 'Gift for Other')], default='Shared', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Now', 'Now'), ('Soon', 'Soon'), ('Not urgent', 'Not urgent'), ('Considering', 'Considering'), ('Do not need', 'Do not need')], default='Now', max_length=50, null=True),
        ),
    ]
