# Generated by Django 2.0.1 on 2018-01-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20180118_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping',
            old_name='completed',
            new_name='archive',
        ),
        migrations.AddField(
            model_name='shopping',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
