# Generated by Django 2.0.1 on 2018-01-24 15:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20180123_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='follow_up',
            field=models.BooleanField(default=False, verbose_name='Complete (but follow-up)'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='store_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Grocery', 'Grocery'), ('Other', 'Other')], default='Grocery', max_length=13, null=True),
        ),
    ]
