# Generated by Django 2.0.1 on 2018-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20180124_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='store',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Other', 'Other')], default='Grocery', max_length=100, null=True),
        ),
    ]
