# Generated by Django 2.0.1 on 2018-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_shopping_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='store_type',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='store',
            field=models.CharField(blank=True, default='Grocery', max_length=100, null=True, verbose_name='Where to buy?'),
        ),
    ]
