# Generated by Django 2.0.1 on 2018-01-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20180124_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
