# Generated by Django 2.0.1 on 2018-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_shopping_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
