# Generated by Django 2.0.1 on 2018-01-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20180125_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='repeat_item',
            field=models.BooleanField(default=False, verbose_name='Repeat Purchase?'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='store',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Store', 'Store'), ('Online', 'Online')], default='Grocery', max_length=100, null=True),
        ),
    ]
