# Generated by Django 2.0.1 on 2018-01-25 14:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20180125_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='stores',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Grocery', 'Grocery'), ('Store', 'Store'), ('Online', 'Online')], default='Grocery', max_length=100, null=True),
        ),
    ]
