# Generated by Django 2.0.1 on 2018-02-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20180201_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
