# Generated by Django 2.0.1 on 2018-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_shopping_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='wish_list',
            field=models.BooleanField(default=False),
        ),
    ]
