# Generated by Django 2.0.1 on 2018-02-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_shopping_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='in_list',
            field=models.BooleanField(default=True, verbose_name='Currently In List'),
        ),
    ]
