# Generated by Django 2.0.1 on 2018-02-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_shopping_in_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='archive',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='in_list',
            field=models.BooleanField(default=False, verbose_name='In List?'),
        ),
    ]
