# Generated by Django 2.0.1 on 2018-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20180201_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='in_list',
            field=models.BooleanField(default=True, verbose_name='In List?'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
