# Generated by Django 2.0.1 on 2018-01-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('quick_facts', models.EmailField(blank=True, max_length=1000, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('connection_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Colleague', 'Colleague'), ('Social Acquaintance', 'Social Acquaintance'), ('Friend', 'Friend'), ('Family', 'Family'), ('Neighbor', 'Neighbor'), ('Other', 'Other')], max_length=58, null=True)),
                ('sub_connection_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Deloitte', 'Deloitte'), ('Kellogg', 'Kellogg'), ('Navy', 'Navy'), ('Client', 'Client'), ('Networking Event', 'Networking Event'), ('Other', 'Other')], max_length=51, null=True)),
                ('connection_quality', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=20, null=True)),
                ('introduced_by', models.CharField(blank=True, max_length=100, null=True)),
                ('introduced_at', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_connection_info', models.EmailField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('jobs', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('significant_other', models.CharField(blank=True, max_length=100, null=True)),
                ('children', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_bio_info', models.TextField(blank=True, max_length=1000, null=True)),
                ('birthday', models.CharField(blank=True, max_length=200, null=True)),
                ('last_contacted', models.DateField(blank=True, max_length=100, null=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_added'],
            },
        ),
    ]
