# Generated by Django 2.0.1 on 2018-01-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180116_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
