# Generated by Django 2.0.1 on 2018-01-31 15:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180116_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='children',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='extra_bio_info',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='extra_connection_info',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='introduced_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='introduced_by',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='school',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='significant_other',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='sub_connection_type',
        ),
        migrations.AddField(
            model_name='contacts',
            name='file_upload',
            field=models.FileField(blank=True, default='None', null=True, upload_to='contacts/%Y/%M/'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='connection_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Professional', 'Professional'), ('Friend', 'Friends'), ('Family,', 'Family'), ('Acquaintance', 'Acquaintance')], max_length=40, null=True),
        ),
    ]
