# Generated by Django 2.0.1 on 2018-01-31 20:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180131_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='quick_facts',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='contacts',
            name='quick_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='connection_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Professional', 'Professional'), ('Friend', 'Friends'), ('Family,', 'Family'), ('Acquaintance', 'Acquaintance'), ('Navy', 'Navy')], max_length=45, null=True),
        ),
    ]
