# Generated by Django 2.0.1 on 2018-01-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('task_specifics', models.TextField(blank=True, max_length=1000, null=True)),
                ('task_urgency', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], default='(not specified)', max_length=50, null=True)),
                ('task_importance', models.CharField(blank=True, choices=[('Important', 'Important'), ('Not Important', 'Not Important')], default='(not specified)', max_length=50, null=True)),
                ('task_category', models.CharField(blank=True, choices=[('Client Project', 'Client Project'), ('PRD', 'PRD'), ('Professional Network', 'Professional Network'), ('Personal Relationships', 'Personal Relationships'), ('Hobby', 'Hobby')], default='(not specified)', max_length=50, null=True)),
                ('task_completed', models.BooleanField(default=False)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_added'],
            },
        ),
    ]
