# Generated by Django 2.0.1 on 2018-01-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='task_category',
            field=models.CharField(blank=True, choices=[('Deloitte', 'Deloitte'), ('Navy', 'Navy'), ('Personal', 'Personal')], default='(not specified)', max_length=50, null=True),
        ),
    ]
