# Generated by Django 2.0.1 on 2018-01-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20180122_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='task_followup',
            field=models.BooleanField(default=False),
        ),
    ]
