# Generated by Django 2.0.1 on 2018-01-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_to_do_list_task_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='task_archive',
            field=models.BooleanField(default=False),
        ),
    ]
